### ISSUE TITLE
Only reports for py files in a puppet manifest directory

### ISSUE THREAD

**Issue by dfuentes77** [GeriatricJacob/line-count#10]
After ctrl-shift-L and choosing Puppet, ctrl-alt-shift-L in puppet directory reports only py files

**Comment by roemhildtg** [comment]
I have a related issue. After I use it, it only reports on one file. I've tried using ctrl-alt-shift-L and using the Packages > Line Count. 

Also the output for that single file are blank:

```

Line counts for project Y:\apps\geomoose2\maps\util\woHydString.map.
Generated by the Atom editor package Line-Count on October 14 2015 15:08.
Counts are in order of source, comments, and total.

Files
-----

Directories
-----------

Types
-----

Total
-----
```
